name: learning

on:
  schedule:
    - cron: '47 14 * * *'  # Daily at 14:50 UTC
  push:
    branches:
      - main

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        env:
          PAT_TOKEN: ${{ secrets.AT }}
        run: |
          git config --global user.name '1-Nishanth-1'
          git config --global user.email '1-Nishanth-1@users.noreply.github.com'
          git add report.txt
          git commit -m "Automated report"
          git push https://1-Nishanth-1:${PAT_TOKEN}@github.com/1-Nishanth-1/trying-github-action.git HEAD:main
